### ISSUE TITLE
Latest update (Ver. 4.0.5.1) crashes game upon launch

### ISSUE THREAD

**Issue by moonchild23** [MidoriKami/NoTankYou#26]
Here's what the last few lines of the XIVLauncher log file says:
```
2022-07-01 17:23:35.904 +10:00 [INF] [PLUGINM] Loading plugin NoTankYou
2022-07-01 17:23:35.912 +10:00 [INF] [LOCALPLUGIN] Loading NoTankYou.dll
2022-07-01 17:23:35.976 +10:00 [INF] [NoTankYou] Loading Localization for en
2022-07-01 17:23:36.246 +10:00 [INF] [GameFontManager] NewFontRef: Building GameFontStyle(Axis18, 18pt, skew=0, weight=0) right now, as it is called while BuildFonts is already in progress yet atlas build has not been called yet.
```
![image_2022-07-01_173418192](https://user-images.githubusercontent.com/65237767/176847152-071c39f7-18f7-4e0f-819a-5e4beba1a5f3.png)
Issue goes away if plugin is uninstalled.

This is my config, if that helps:
```
{
  "$type": "NoTankYou.Data.Configuration, NoTankYou",
  "DeveloperMode": false,
  "Version": 1,
  "DebugSettings": {
    "$type": "NoTankYou.Data.DebugSettings, NoTankYou",
    "ContentDirector": true
  },
  "ModuleSettings": {
    "$type": "NoTankYou.Data.ModuleSettings, NoTankYou",
    "Dancer": {
      "$type": "NoTankYou.Data.Modules.DancerModuleSettings, NoTankYou",
      "Enabled": true,
      "SoloMode": false,
      "Priority": 1,
      "DutiesOnly": true
    },
    "Food": {
      "$type": "NoTankYou.Data.Modules.FoodModuleSettings, NoTankYou",
      "FoodEarlyWarningTime": 600,
      "SavageDuties": false,
      "UltimateDuties": false,
      "DisableInCombat": true,
      "ExtremeUnreal": false,
      "Enabled": false,
      "SoloMode": false,
      "Priority": 1,
      "DutiesOnly": true
    },
    "Sage": {
      "$type": "NoTankYou.Data.Modules.SageModuleSettings, NoTankYou",
      "Enabled": true,
      "SoloMode": false,
      "Priority": 1,
      "DutiesOnly": true
    },
    "Scholar": {
      "$type": "NoTankYou.Data.Modules.ScholarModuleSettings, NoTankYou",
      "Enabled": true,
      "SoloMode": false,
      "Priority": 1,
      "DutiesOnly": true
    },
    "Summoner": {
      "$type": "NoTankYou.Data.Modules.SummonerModuleSettings, NoTankYou",
      "Enabled": true,
      "SoloMode": false,
      "Priority": 1,
      "DutiesOnly": true
    },
    "Tank": {
      "$type": "NoTankYou.Data.Modules.TankModuleSettings, NoTankYou",
      "DisableInAllianceRaid": true,
      "CheckAllianceStances": false,
      "Enabled": true,
      "SoloMode": false,
      "Priority": 1,
      "DutiesOnly": true
    },
    "BlueMage": {
      "$type": "NoTankYou.Data.Modules.BlueMageModuleSettings, NoTankYou",
      "Mimicry": false,
      "TankStance": false,
      "BasicInstinct": false,
      "Enabled": true,
      "SoloMode": false,
      "Priority": 1,
      "DutiesOnly": true
    },
    "FreeCompany": {
      "$type": "NoTankYou.Data.Modules.FreeCompanyModuleSettings, NoTankYou",
      "ScanMode": 0,
      "BuffCount": 2,
      "BuffList": [
        0,
        0
      ],
      "Enabled": false,
      "SoloMode": true,
      "Priority": 1,
      "DutiesOnly": false
    }
  },
  "DisplaySettings": {
    "$type": "NoTankYou.Data.DisplaySettings, NoTankYou",
    "PartyOverlay": {
      "$type": "NoTankYou.Data.Overlays.PartyOverlaySettings, NoTankYou",
      "Enabled": true,
      "WarningText": true,
      "PlayerName": false,
      "JobIcon": false,
      "FlashingEffects": false,
      "WarningTextColor": {
        "$type": "System.Numerics.Vector4, System.Private.CoreLib",
        "X": 0.8,
        "Y": 0.2,
        "Z": 0.2,
        "W": 1.0
      },
      "WarningOutlineColor": {
        "$type": "System.Numerics.Vector4, System.Private.CoreLib",
        "X": 1.0,
        "Y": 0.0,
        "Z": 0.0,
        "W": 1.0
      },
      "DisableInSanctuary": false
    },
    "BannerOverlay": {
      "$type": "NoTankYou.Data.Overlays.BannerOverlaySettings, NoTankYou",
      "Enabled": false,
      "Scale": 0.4,
      "WarningCount": 8,
      "Mode": 1,
      "Position": {
        "$type": "System.Numerics.Vector2, System.Private.CoreLib",
        "X": 5.0,
        "Y": 392.0
      },
      "Reposition": false,
      "WarningShield": false,
      "WarningText": true,
      "Icon": true,
      "PlayerNames": true,
      "IconText": false,
      "DisableInSanctuary": false
    },
    "TippyOverlay": {
      "$type": "NoTankYou.Data.Overlays.TippyOverlaySettings, NoTankYou",
      "DisableInSanctuary": false,
      "WarningFrequency": 30,
      "Enabled": false,
      "SoloMode": false,
      "Priority": 1,
      "DutiesOnly": true
    }
  },
  "SystemSettings": {
    "$type": "NoTankYou.Data.SystemSettings, NoTankYou",
    "DisablePartyListVisibilityChecking": false,
    "Blacklist": {
      "$type": "NoTankYou.Data.Components.BlacklistSettings, NoTankYou",
      "Enabled": false,
      "BlacklistedZones": []
    }
  }
}
```

**Comment by MidoriKami** [comment]
If you are able to reproduce the crash can you send your entire `dalamud.log` file please.

**Comment by moonchild23** [comment]
Here's my [dalamud.log](https://github.com/MidoriKami/NoTankYou/files/9030264/dalamud.log) that I saved from when the crash occurred, and [dalamud.boot.log](https://github.com/MidoriKami/NoTankYou/files/9030266/dalamud.boot.log) from right now (after playing for a bit).

**Comment by MidoriKami** [comment]
I have forwarded this issue to the Dalamud team, this seems to be an internal issue not specific to NoTankYou.

Actual exception info for other that come across this:`
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at ImGuiNET.ImGuiNative.ImFontAtlas_Build(ImGuiNET.ImFontAtlas*)
--------------------------------
   at Dalamud.Interface.Internal.InterfaceManager.SetupFonts(Boolean)
   at Dalamud.Interface.Internal.InterfaceManager.RebuildFontsInternal()
   at ImGuiScene.RawDX11Scene.Render()
   at Dalamud.Interface.Internal.InterfaceManager.PresentDetour(IntPtr, UInt32, UInt32)
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr)
```
