### ISSUE TITLE
Error spam from BannerController.DrawListWarnings

### ISSUE THREAD

**Issue by sersorrel** [MidoriKami/NoTankYou#61]
```
21:41:27.398 | ERR | Exception during raise of "Void <InvokeSafely>b__0()"
    System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
       at System.Collections.Generic.List`1.get_Item(Int32 index)
       at KamiToolKit.Nodes.ListNode`1.get_Item(Int32 index) in /work/repo/KamiToolKit/Nodes/ListNode.cs:line 244
       at NoTankYou.Controllers.BannerController.DrawListWarnings(IEnumerable`1 warnings) in /work/repo/NoTankYou/Controllers/BannerController.cs:line 105
       at NoTankYou.Controllers.BannerController.Draw(IEnumerable`1 warnings) in /work/repo/NoTankYou/Controllers/BannerController.cs:line 90
       at Dalamud.Game.FrameworkPluginScoped.OnUpdateForward(IFramework framework) in C:\goatsoft\companysecrets\dalamud\\Game\Framework.cs:line 623
       at Dalamud.Utility.EventHandlerExtensions.<>c__DisplayClass4_1.<InvokeSafely>b__0() in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 99
       at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
```

I don't have any particular details, sorry. I was in a party but not a duty, the other party member was not in the same zone as me.

**Comment by MidoriKami** [comment]
Gonna assume this was due to the SetText issue, and that earlier in your log there was likely some exceptions thrown during the creation of my nodes.
